name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Modifie selon la version de Python que tu utilises

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assure-toi que tu as un fichier requirements.txt

      - name: Run tests
        run: |
          pytest  # Assure-toi que tu utilises pytest ou l'outil de tests que tu préfères
